name: DioBrowser
options:
  bundleIdPrefix: com.lightbrowser
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  DioBrowser:
    type: application
    platform: iOS
    sources:
      - path: Sources
        type: group
    resources:
      - path: Resources
        type: group
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.lightbrowser.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
    entitlements:
      path: Resources/DioBrowser.entitlements
      properties:
        com.apple.security.app-sandbox: true

  DioBrowserTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        type: group
    dependencies:
      - target: DioBrowser
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/DioBrowser.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/DioBrowser"
        BUNDLE_LOADER: "$(TEST_HOST)"
